### ISSUE TITLE
Udp traffic possible?

### ISSUE THREAD

**Issue by blahdy** [nneonneo/socks5-ios#2]
Forgive me if the question is dumb. So far I'm using trollstore, built some guy's fork of your project with the address changing position (to avoid burn in). During build I've added all background capabilities and it is more stable than tetherme even with the screen locked. 

I'm using proxifier on my mac and that should support udp.

**Comment by nneonneo** [comment]
Thanks for your interest in the project! UDP is unfortunately not supported by microsocks, the underlying library (https://github.com/cellularmitosis/socks5-ios/blob/25ac7b0ba735dee6795d54933696955cd950f06a/microsocks/sockssrv.c#L107). However, UDP is supported in my Python-based successor project, https://github.com/nneonneo/iOS-SOCKS-Server. I realize that doesn’t support backgrounding though; I would certainly be interested in any contributions for improving UDP support or for your backgrounding changes. RobertOn Jun 16, 2024, at 4:47 AM, blahdy ***@***.***> wrote:﻿
Forgive me if the question is dumb. So far I'm using trollstore, built some guy's fork of your project with the address changing position (to avoid burn in). During build I've added all background capabilities and it is more stable than tetherme even with the screen locked.
I'm using proxifier on my mac and that should support udp.

**Comment by blahdy** [comment]
Umh, I just enabled in xcode all the background capabilities, that's all I did. And it's backgrounding perfectly.

**Comment by blahdy** [comment]
I did find a microsocks fork with udp support though

https://github.com/ninjken/microsocks

I'll try to build using that, but if it fails and chatgpt won't help me - nothing I can do.

**Comment by nneonneo** [comment]
Interesting, yes, the develop branch looks like it supports UDP. It *should* be a drop-in replacement. If it works let me know; I’ll pull the changes in from the fork & update the microsocks to match. 

Also: a change to the build files to support backgrounding would still be useful! Please do feel free to file a pull request; it would definitely help make this project more useful!

**Comment by nneonneo** [comment]
Ok it’s *almost* a drop-in replacement; you do have apply this one little patch to microsocks: https://github.com/nneonneo/microsocks/commit/e7c538672ae5d67e9af73f7a008e50cfaf8e523a

**Comment by blahdy** [comment]
Will try when I get home!

**Comment by blahdy** [comment]
nah, too much for my plate
<img width="1512" alt="Снимок экрана 2024-06-16 в 14 05 57" src="https://github.com/nneonneo/socks5-ios/assets/9033590/312706b4-b8b3-44ab-9014-d167f8f27559">
also, silly me - proxifier doesn't do udp, so facepalm here. need to look into alternatives first

**Comment by blahdy** [comment]
there are a couple of proxifier alternatives for macos, so that should be covered.

I'll also look into properly adding location capability, if you can help out with "Use of undeclared identifier 'cmd'" and "Use of undeclared identifier 'i'"

**Comment by nneonneo** [comment]
I got a chance to check it out, so I fixed up `microsocks` to build properly with UDP support. I've also tested the UDP support using `udpchk.py` from https://github.com/semigodking/socks5chk, so it *should* work properly.

I haven't integrated the other changes (backgrounding, screensaver) yet.

**Comment by blahdy** [comment]
tested with [tun2socks](https://github.com/xjasonlyu/tun2socks) and it seems to be working blazing fast. much faster than proxifier

**Comment by prototype0z** [comment]
Would you be able to provide the working ipa file? I also would like to install it through trollstore but can't get it working correctly in Xcode.

**Comment by prototype0z** [comment]
Thanks for relying back but I still can't get the ipa file or compiled xcode to run the app correctly via trollstore. Getting a running error: 4884. On iPhone 13 pro max iOS 17.0
![IMG_8075](https://github.com/user-attachments/assets/0602fc1c-7883-43c9-9220-62820f8594fc)

**Comment by blahdy** [comment]
> Thanks for relying back but I still can't get the ipa file or compiled xcode to run the app correctly via trollstore. Getting a running error: 4884. On iPhone 13 pro max iOS 17.0
> 
> ![IMG_8075](https://github.com/user-attachments/assets/0602fc1c-7883-43c9-9220-62820f8594fc)
> 
> 

That's not an error 🤦🏻‍♂️ 4884 is the port

You're not sharing internet. Your phone's ip will be where the error's at.

Are you sure you need this app?
